### ISSUE TITLE
pod install fails

### ISSUE THREAD

**Issue by crobertsbmw** [mohpor/CurvedLabel#1]
I cloned the repo and tried to run `pod install` from the Example directory. I received this error:

```
[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `CurvedLabel_Tests`..

 #  from /Users/croberts/CurvedLabel/Example/Podfile:5
 #  -------------------------------------------
 #  
 >  target 'CurvedLabel_Tests', :exclusive => true do
 #    pod "CurvedLabel", :path => "../"
 #  -------------------------------------------

```

**Comment by mohpor** [comment]
@crobertsbmw 
This is because of the Cocoapods changes since last time I've updated the repo. To my knowledge, Cocoapods doesn't support local pods this way anymore.
Please refer to https://gist.github.com/radiospiel/2009100 for more info.
